import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Conter App",
  description:
    "Generated by create next app and developed by Shivam Abraham to understand the Hooks and Components",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="keywords"
          content="shivam,abraham, React Counter App, Shivam Abraham, React Hooks, React Components"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
